server:
  port: 8081

static-locations:
  classpath: /static/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bughome.springboot.model

spring:
  #热部署插件
  devtools:
    restart:
      #需要实时更新的目录
      additional-paths: resources/**,static/**,templates/**

person:
  lastname: zhangsan
  age: 18
  boss: false
  birth: 2002/11/16
  maps: {k1: 1, K2: 2}
  list: [lisi, wangwu]
  Dog:
    name: wangcai
    age: 5